#!/bin/bash
notify-send 'Daily backup' 'Do not turn off computer' --icon=dialog-information
wget https://raw.githubusercontent.com/rubo77/rsync-homedir-excludes/master/rsync-homedir-excludes.txt -O /var/tmp/ignorelist
rsync -aP --exclude-from=/var/tmp/ignorelist /home/$USER/ /media/cherries/HomeFolderBackups/$HOSTNAME/
notify-send 'Daily backup' 'Done backing up.' --icon=dialog-information  
