#! /usr/bin/env python3
"""Script that runs using cron on my raspberry pi to notify me if my website is down."""

import urllib.request
import smtplib
import datetime
import socket
site = 'http://www.matthewoneill.com'
blog = site + '/oop'

def log(code, codeBlog):
   filename = '/home/pi/.{}.log'.format(site.split('.')[-2])
   date = str(datetime.datetime.now()).split('.')[0]
   nolines = 0
   try:
      for line in open(filename):
         nolines += 1
      nolines = nolines * nolines
   except IOError:
      nolines = 0
   with open(filename, 'a') as fo:
      fo.write(str(nolines+1) + ': Site: ' + date + ' ' + str(code) + '\n')
      fo.write(str(nolines+1) + ': Blog: ' + date + ' ' + str(codeBlog) + '\n')

def sendMail(code, codeBlog):
   global site, blog
   server = 'localhost'
   fromAddress = 'info@matthewoneill.com'
   toAddress = '14matthewoneill14@gmail.com'
   subject = 'Info from your Raspberry Pi'
   message = """\
From: {}
To: {}
Subject: {}

{} returned the code: {}.
{} returned the code: {}.
""".format(fromAddress, toAddress, subject, site, code, blog, codeBlog)
   
   smtpserver = smtplib.SMTP(server)
   smtpserver.sendmail(fromAddress, toAddress, message)
   smtpserver.quit()

def getCode(site):
   try:
      code = urllib.request.urlopen(site).getcode()
   except urllib.request.HTTPError as e:
      code = e.code()
   except urllib.request.URLError as e:
      code = str(e.reason)
   except urllib.error.URLError as e:
      raise e
      code = str(e.reason)
   return code

if __name__ == "__main__":
   
   code = getCode(site)
   codeBlog = getCode(blog)
   log(code, codeBlog)
   if code != 200 or codeBlog != 200:
      sendMail(code, codeBlog)  

